name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Lint client
        run: npm run lint
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Lint server
        run: npm run lint
        working-directory: ./server

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install client dependencies
        run: npm install
        working-directory: ./client
  
      - name: test client
        run: npm run test
        working-directory: ./client
  
      - name: Install server dependencies
        run: npm install
        working-directory: ./server
  
      - name: test server
        run: npm run test
        working-directory: ./server